[toolchain]
anchor_version = "0.32.1"
package_manager = "bun"
solana_version = "2.3.13"

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "AtoUtAszTsCzvdm54bKsc28PpYnNaA2pg7zYkyXPtiCw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = true
